print("Hello! My name is ChatBot")
print("I was created in 2021")
name = input("Please, remind me your name")
print("What a great name you have," + name)
print("let me guess your age")
print("Enter remainders of dividing your age by 3, 5 and 7")
p = int(input())
pp = int(input())
ppp = int(input())
qazi = ((p * 70 + pp * 21 + ppp * 15)%105)
print("Your age is %s; that's a good time to start programming" %qazi)
print("Now i will prove to you that i can count to any number you want")
a = int(input())
for i in range(a+1):
    print(i,"!")
print("Let's test your programming knowledge")
a = ("1.To repeat a statement multiple times")
b = ("2.Todecompose a program into several small subroutimes")
c = ("3.To determine the execution time of a program")
d = ("4.To interrupt the execution of a program")
print("Why do we use methods?")
print( a )
print( b )
print( c )
print( d )
q = int(input())
while q!=2:
    print("Please,try again")
    q = int(input())
else:
    print("Completed, have a nice day")
print("Congratulations, have a nice day!")


